### ISSUE TITLE
Incomplete usage info

### ISSUE THREAD

**Issue by VitalyVaryvdin** [jhauberg/cards.py#160]
Having hard time understanding how to use this.
Can't generate love-letter-templated example due to crash (https://i.imgur.com/QpwYQjd.png)
Dungeon deck couldn't be generated properly either - icons folder isn't carried over, and even after I move it manually they fail to get loaded - HTML doesn't replace "{ icon }" references with correct image path.

Also, syntax you utilize isn't documented anywhere in the readme, a little bit confusing to work with.

**Comment by jhauberg** [comment]
Thanks for your feedback!

> Having hard time understanding how to use this.

I totally get that. At some point I was working on a document to explain usage in more details, but never managed to complete it. I will just put up [what I have](https://github.com/jhauberg/cards.py/tree/master/docs), though incomplete.

> Can't generate love-letter-templated example due to crash

I was made aware of the problem with the Love Letter example [previously](https://github.com/jhauberg/cards.py/issues/159#issuecomment-355496431), but never got around to fixing it. It only affects Windows- unfortunate, because I don't have a copy/machine to test on.

On macOS, this works (assuming located in project root):

```shell
$ python3 -m cards make example/love-letter-templated -o ~/Desktop
```

> Dungeon deck couldn't be generated properly either

There's definitely some problems with this example. I will see what I can do.

Though it doesn't work right now, this is all that should be needed to build it (assuming located in project root):

```shell
$ python3 -m cards make ~/Downloads/dungeon-deck-master/src -d ~/Downloads/dungeon-deck-master/src/definitions.csv -o ~/Desktop --disable-backs
```

**Comment by VitalyVaryvdin** [comment]
Thank you for fast reply :)

Well, I guess I'll continue digging under WSL then. Do you plan to continue your work on the project?

**Comment by jhauberg** [comment]
To be completely honest, I don't think I will.

I haven't been active on this project for many years now, and coming back to it yesterday to see if I could easily fix your problem made it pretty clear that maintenance requires more effort than I am willing to commit. If anything, I would want to start over completely 😅

Consider alternatives.
